
modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
issueTrackerURL="https://github.com/lanAnderson/IanAnderson-Tweaks/issues"

[[mods]]
modId = "iantweaks"
version = "${file.jarVersion}"
displayName = "IanAnderson Tweaks"
displayURL="https://github.com/lanAnderson/IanAnderson-Tweaks"
logoFile="iantweaks.png"
authors = "IanAnderson"
description = '''
Tweaks for IanAnderson's Modpack
'''

[[dependencies.iantweaks]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iantweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
